<a href="https://colab.research.google.com/github/achuga200/colabProjectsWQU/blob/master/OneHotEncoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Convert to one hot encoding Using TensorFlow

import tensorflow as tf
import pandas as pd

text = 'My cat is a great cat'
tokens = text.lower().split()

vocab = set(tokens)
vocab = pd.Series(range(len(vocab)), index=vocab)

word_ids = vocab.loc[tokens].values

inputs = tf.placeholder(tf.int32, [None])
# TensorFlow has an operation for one-hot encoding
one_hot_inputs = tf.one_hot(inputs, len(vocab))
transformed = tf.Session().run(one_hot_inputs, {inputs: word_ids})


print (transformed)

[[1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]]


Steps to follow:

Convert the text to Lower Case

Word Tokenize

Get its integer value i.e the position by using LabelEncoder()

Get one hot encoding of the word by referring to the label encoded values by 

using to_categorical()